#Numpy assignment

In [1]:
import numpy as np
import pandas as pd

# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [2]:
arr = np.arange(6)
print("1. NumPy array 'arr' and its data type:")
print(arr)
print("Data type:", arr.dtype)
print("\n")

1. NumPy array 'arr' and its data type:
[0 1 2 3 4 5]
Data type: int64




# 2. Given a NumPy array 'arr', check if its data type is float64.


In [3]:
arr = np.array([1.5, 2.6, 3.7])
print("2. Checking if the array data type is float64:")
print(arr.dtype == np.float64)
print("\n")

2. Checking if the array data type is float64:
True




# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.


In [4]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("3. NumPy array with complex128 data type:")
print(arr)
print("\n")

3. NumPy array with complex128 data type:
[1.+2.j 3.+4.j 5.+6.j]




# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.


In [5]:
arr = np.array([1, 2, 3])
arr_float32 = arr.astype(np.float32)
print("4. Converted NumPy array to float32:")
print(arr_float32)
print("Data type:", arr_float32.dtype)

4. Converted NumPy array to float32:
[1. 2. 3.]
Data type: float32


# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


In [6]:
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print("5. Converted float64 array to float32:")
print(arr_float32)
print("Data type:", arr_float32.dtype)

5. Converted float64 array to float32:
[1.1 2.2 3.3]
Data type: float32


# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.


In [8]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1, 2, 3, 4, 5])
print("6. Array attributes (shape, size, data type):")
print(array_attributes(arr))

6. Array attributes (shape, size, data type):
((5,), 5, dtype('int64'))


# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


In [9]:
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("7. Array dimensionality:")
print(array_dimension(arr))

7. Array dimensionality:
2


# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.


In [10]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3])
print("8. Item size and total size in bytes:")
print(item_size_info(arr))
print("\n")

8. Item size and total size in bytes:
(8, 24)




# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.


In [11]:
def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("9. Array strides:")
print(array_strides(arr))

9. Array strides:
(24, 8)


# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.


In [12]:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("10. Shape and strides of the array:")
print(shape_stride_relationship(arr))

10. Shape and strides of the array:
((2, 3), (24, 8))


# 11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.


In [13]:
def create_zeros_array(n):
    return np.zeros(n)

print("11. Array of zeros with n elements:")
print(create_zeros_array(5))

11. Array of zeros with n elements:
[0. 0. 0. 0. 0.]


# 12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.


In [14]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print("12. 2D array of ones:")
print(create_ones_matrix(3, 4))

12. 2D array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.


In [15]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print("13. NumPy array with a range:")
print(generate_range_array(1, 10, 2))

13. NumPy array with a range:
[1 3 5 7 9]


# 14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive).


In [16]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print("14. Linearly spaced values:")
print(generate_linear_space(0, 1, 5))

14. Linearly spaced values:
[0.   0.25 0.5  0.75 1.  ]


# 15. Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size n x n using numpy.eye.


In [17]:
def create_identity_matrix(n):
    return np.eye(n)

print("15. Identity matrix of size n x n:")
print(create_identity_matrix(4))

15. Identity matrix of size n x n:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 16. Write a function that takes a Python list and converts it into a NumPy array.


In [18]:
def list_to_numpy_array(lst):
    return np.array(lst)

print("16. Converted Python list to NumPy array:")
print(list_to_numpy_array([1, 2, 3, 4, 5]))

16. Converted Python list to NumPy array:
[1 2 3 4 5]


# 17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.


In [19]:
arr = np.array([1, 2, 3, 4, 5])
arr_view = arr.view()
print("17. Original array and its view:")
print("Original array:", arr)
print("View:", arr_view)

17. Original array and its view:
Original array: [1 2 3 4 5]
View: [1 2 3 4 5]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.


In [20]:
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("18. Concatenated arrays:")
print(concatenate_arrays(arr1, arr2, axis=0))

18. Concatenated arrays:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.


In [22]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Changed arr1 to have 2 rows
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print("19. Horizontally concatenated arrays (after modifying arrays):")
print(np.concatenate((arr1, arr2), axis=1))


19. Horizontally concatenated arrays (after modifying arrays):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.


In [23]:
def vertical_stack(arr_list):
    return np.vstack(arr_list)

arr_list = [np.array([1, 2, 3]), np.array([4, 5, 6])]
print("20. Vertically stacked arrays:")
print(vertical_stack(arr_list))

20. Vertically stacked arrays:
[[1 2 3]
 [4 5 6]]


# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.


In [24]:
def create_integer_range(start, stop, step):
    return np.arange(start, stop + 1, step)

print("21. Integer array within a specified range:")
print(create_integer_range(1, 10, 2))

21. Integer array within a specified range:
[1 3 5 7 9]


# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).


In [25]:
def generate_spaced_values():
    return np.linspace(0, 1, 10)

print("22. Equally spaced values between 0 and 1:")
print(generate_spaced_values())

22. Equally spaced values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


In [26]:
def generate_logarithmic_space():
    return np.logspace(0, 3, 5)

print("23. Logarithmically spaced values:")
print(generate_logarithmic_space())

23. Logarithmically spaced values:
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.


In [27]:
np.random.seed(0)
arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print("24. Pandas DataFrame with random integers:")
print(df)

24. Pandas DataFrame with random integers:
    A   B   C
0  45  48  65
1  68  68  10
2  84  22  37
3  88  71  89
4  89  13  59


# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.


In [28]:
def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

# Sample DataFrame with negative values
df = pd.DataFrame({'A': [1, -2, 3], 'B': [-1, -5, 6], 'C': [7, 8, 9]})
print("25. DataFrame after replacing negative values:")
print(replace_negatives(df, 'B'))

25. DataFrame after replacing negative values:
   A  B  C
0  1  0  7
1 -2  0  8
2  3  6  9


# 26. Access the 3rd element from the given NumPy array.


In [29]:
arr = np.array([10, 20, 30, 40, 50])
print("26. 3rd element in the array:")
print(arr[2])

26. 3rd element in the array:
30


# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.


In [30]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("27. Element at index (1, 2):")
print(arr_2d[1, 2])

27. Element at index (1, 2):
6


# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.


In [31]:
arr = np.array([3, 8, 2, 10, 5, 7])
print("28. Elements greater than 5:")
print(arr[arr > 5])

28. Elements greater than 5:
[ 8 10  7]


# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("29. Sliced elements from index 2 to 5:")
print(arr[2:6])

29. Sliced elements from index 2 to 5:
[3 4 5 6]


# 30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.


In [33]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("30. Extracted sub-array:")
print(arr_2d[0:2, 1:3])

30. Extracted sub-array:
[[2 3]
 [5 6]]


# 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.


In [34]:
def extract_elements_by_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])
print("31. Extracted elements in specific order:")
print(extract_elements_by_indices(arr, row_indices, col_indices))

31. Extracted elements in specific order:
[3 5 7]


# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.


In [35]:
def filter_elements_by_threshold(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 4, 7, 10])
print("32. Filtered elements greater than threshold:")
print(filter_elements_by_threshold(arr, 5))

32. Filtered elements greater than threshold:
[ 7 10]


# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.


In [36]:
def extract_from_3d_array(arr, x_indices, y_indices, z_indices):
    return arr[x_indices, y_indices, z_indices]

arr_3d = np.random.randint(1, 10, size=(3, 3, 3))
x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 0, 2])
z_indices = np.array([2, 1, 0])
print("33. Extracted elements from 3D array:")
print(extract_from_3d_array(arr_3d, x_indices, y_indices, z_indices))

33. Extracted elements from 3D array:
[2 1 1]


# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.


In [37]:
def elements_meeting_conditions(arr, condition1, condition2):
    return arr[np.logical_and(condition1, condition2)]

arr = np.array([10, 15, 20, 25, 30])
print("34. Elements meeting both conditions:")
print(elements_meeting_conditions(arr, arr > 10, arr < 30))

34. Elements meeting both conditions:
[15 20 25]


# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.


In [38]:
def extract_elements_by_row_col(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1])
col_indices = np.array([2, 1])
print("35. Extracted elements using row and column indices:")
print(extract_elements_by_row_col(arr_2d, row_indices, col_indices))

35. Extracted elements using row and column indices:
[3 5]


# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_broadcasted = arr + 5
print("36. Array after adding scalar value of 5:")
print(arr_broadcasted)

36. Array after adding scalar value of 5:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.


In [40]:
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
arr_broadcasted = arr2 * arr1.T
print("37. Result after broadcasting multiplication:")
print(arr_broadcasted)

37. Result after broadcasting multiplication:
[[ 2  2  2  2]
 [ 6  6  6  6]
 [12 12 12 12]]


# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.


In [43]:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])
arr_broadcasted = arr1.T + arr2
print("38. Result after broadcasting addition:")
print(arr_broadcasted)

38. Result after broadcasting addition:
[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.


In [44]:
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
arr_broadcasted = arr1 + arr2
print("39. Result after broadcasting addition:")
print(arr_broadcasted)

39. Result after broadcasting addition:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.


In [45]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])
try:
    arr_broadcasted = arr1[:, :2] * arr2
    print("40. Result after broadcasting multiplication:")
    print(arr_broadcasted)
except ValueError as e:
    print("Error:", e)

40. Result after broadcasting multiplication:
[[ 7 16]
 [36 50]]


# 41. Calculate column-wise mean for the given array:


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
col_mean = np.mean(arr, axis=0)
print("41. Column-wise mean:")
print(col_mean)

41. Column-wise mean:
[2.5 3.5 4.5]


# 42. Find maximum value in each row of the given array:


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print("42. Maximum value in each row:")
print(row_max)

42. Maximum value in each row:
[3 6]


# 43. For the given array, find indices of maximum value in each column.


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
col_max_indices = np.argmax(arr, axis=0)
print("43. Indices of maximum value in each column:")
print(col_max_indices)

43. Indices of maximum value in each column:
[1 1 1]


# 44. For the given array, apply custom function to calculate moving sum along rows.


In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

print("44. Moving sum along rows:")
print(moving_sum(arr))

44. Moving sum along rows:
[[ 1  3  6]
 [ 4  9 15]]


# 45. In the given array, check if all elements in each column are even.


In [50]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
col_all_even = np.all(arr % 2 == 0, axis=0)
print("45. Check if all elements in each column are even:")
print(col_all_even)

45. Check if all elements in each column are even:
[False False False]


# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.


In [51]:
def reshape_array(arr, m, n):
    return arr.reshape(m, n)

original_array = np.array([1, 2, 3, 4, 5, 6])
print("46. Reshaped array:")
print(reshape_array(original_array, 2, 3))

46. Reshaped array:
[[1 2 3]
 [4 5 6]]


# 47. Create a function that takes a matrix as input and returns the flattened array.


In [52]:
def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("47. Flattened matrix:")
print(flatten_matrix(input_matrix))

47. Flattened matrix:
[1 2 3 4 5 6]


# 48. Write a function that concatenates two given arrays along a specified axis.


In [53]:
def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print("48. Concatenated array along axis 0:")
print(concatenate_arrays(array1, array2, axis=0))

48. Concatenated array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.


In [54]:
def split_array(array, indices_or_sections, axis=0):
    return np.array_split(array, indices_or_sections, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("49. Split array:")
print(split_array(original_array, 3, axis=0))

49. Split array:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


# 50. Write a function that inserts and then deletes elements from a given array at specified indices.


In [55]:
def insert_and_delete_elements(array, indices_to_insert, values_to_insert, indices_to_delete):
    array = np.insert(array, indices_to_insert, values_to_insert)
    array = np.delete(array, indices_to_delete)
    return array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
print("50. Array after insertion and deletion:")
print(insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete))

50. Array after insertion and deletion:
[ 1 10  4 11  5]


# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.


In [56]:
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
print("51. Element-wise addition of arr1 and arr2:")
print(arr1 + arr2)

51. Element-wise addition of arr1 and arr2:
[ 5  5 11  7  6]


# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.


In [57]:
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
print("52. Element-wise subtraction of arr2 from arr1:")
print(arr1 - arr2)

52. Element-wise subtraction of arr2 from arr1:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.


In [58]:
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
print("53. Element-wise multiplication of arr1 and arr2:")
print(arr1 * arr2)

53. Element-wise multiplication of arr1 and arr2:
[ 1 10 18 24 35]


# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.


In [59]:
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
print("54. Element-wise division of arr1 by arr2:")
print(arr1 / arr2)

54. Element-wise division of arr1 by arr2:
[2. 2. 2. 2. 2.]


# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.


In [60]:
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
print("55. Element-wise exponentiation of arr1 to the power of arr2:")
print(arr1 ** arr2)

55. Element-wise exponentiation of arr1 to the power of arr2:
[ 1 16 27 16  5]


# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.


In [61]:
def count_substring(arr, substring):
    return np.array([s.count(substring) for s in arr])

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print("56. Occurrences of 'hello':")
print(count_substring(arr, 'hello'))

56. Occurrences of 'hello':
[1 0 1 0 1]


# 57. Write a function that extracts uppercase characters from a NumPy array of strings.


In [62]:
def extract_uppercase(arr):
    return np.array([''.join(filter(str.isupper, s)) for s in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print("57. Extracted uppercase characters:")
print(extract_uppercase(arr))

57. Extracted uppercase characters:
['H' 'W' 'OAI' 'GPT']


# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.


In [63]:
def replace_substring(arr, old_substring, new_substring):
    return np.array([s.replace(old_substring, new_substring) for s in arr])

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print("58. Array after replacing 'apple' with 'orange':")
print(replace_substring(arr, 'apple', 'orange'))

58. Array after replacing 'apple' with 'orange':
['orange' 'banana' 'grape' 'pineorange']


# 59. Write a function that concatenates strings in a NumPy array element-wise.


In [64]:
def concatenate_strings(arr1, arr2):
    return np.array([a + b for a, b in zip(arr1, arr2)])

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print("59. Concatenated strings:")
print(concatenate_strings(arr1, arr2))

59. Concatenated strings:
['HelloOpen' 'WorldAI']


# 60. Write a function that finds the length of the longest string in a NumPy array.


In [65]:
def length_of_longest_string(arr):
    return max(len(s) for s in arr)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print("60. Length of the longest string:")
print(length_of_longest_string(arr))

60. Length of the longest string:
9


# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.


In [66]:
data = np.random.randint(1, 1001, size=100)
print("61. Statistics of the dataset:")
print(f"Mean: {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Variance: {np.var(data)}")
print(f"Standard Deviation: {np.std(data)}")

61. Statistics of the dataset:
Mean: 532.29
Median: 558.5
Variance: 91858.66589999999
Standard Deviation: 303.0819458496332


# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.


In [67]:
data = np.random.randint(1, 101, size=50)
print("62. 25th and 75th percentiles:")
print(f"25th percentile: {np.percentile(data, 25)}")
print(f"75th percentile: {np.percentile(data, 75)}")

62. 25th and 75th percentiles:
25th percentile: 20.5
75th percentile: 68.0


# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.


In [68]:
array1 = np.random.rand(10)
array2 = np.random.rand(10)
print("63. Correlation coefficient between two arrays:")
print(np.corrcoef(array1, array2)[0, 1])

63. Correlation coefficient between two arrays:
0.38171020383883103


# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.


In [69]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print("64. Matrix multiplication:")
print(np.dot(matrix1, matrix2))

64. Matrix multiplication:
[[19 22]
 [43 50]]


# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.


In [70]:
data = np.random.randint(10, 1001, size=50)
print("65. Percentiles and quartiles:")
print(f"10th percentile: {np.percentile(data, 10)}")
print(f"50th percentile (median): {np.percentile(data, 50)}")
print(f"90th percentile: {np.percentile(data, 90)}")
print(f"First quartile: {np.percentile(data, 25)}")
print(f"Third quartile: {np.percentile(data, 75)}")

65. Percentiles and quartiles:
10th percentile: 141.50000000000003
50th percentile (median): 640.0
90th percentile: 911.0
First quartile: 309.5
Third quartile: 781.0


# 66. Create a NumPy array of integers and find the index of a specific element.


In [71]:
def find_index(array, value):
    return np.where(array == value)[0][0]

array = np.array([10, 20, 30, 40, 50])
print("66. Index of element 30:")
print(find_index(array, 30))

66. Index of element 30:
2


# 67. Generate a random NumPy array and sort it in ascending order.


In [72]:
array = np.random.randint(1, 100, size=10)
print("67. Sorted array:")
print(np.sort(array))

67. Sorted array:
[28 35 35 40 45 46 62 72 86 98]


# 68. Filter elements >20 in the given NumPy array.


In [73]:
arr = np.array([12, 25, 6, 42, 8, 30])
print("68. Elements greater than 20:")
print(arr[arr > 20])

68. Elements greater than 20:
[25 42 30]


# 69. Filter elements which are divisible by 3 from a given NumPy array.


In [74]:
arr = np.array([1, 5, 8, 12, 15])
print("69. Elements divisible by 3:")
print(arr[arr % 3 == 0])

69. Elements divisible by 3:
[12 15]


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.


In [75]:
arr = np.array([10, 20, 30, 40, 50])
print("70. Elements between 20 and 40 (inclusive):")
print(arr[(arr >= 20) & (arr <= 40)])

70. Elements between 20 and 40 (inclusive):
[20 30 40]


# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.


In [76]:
arr = np.array([1, 2, 3])
print("71. Byte order of the array:")
print(arr.dtype.byteorder)

71. Byte order of the array:
=


# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.


In [77]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print("72. Array after byte swapping in place:")
print(arr)

72. Array after byte swapping in place:
[16777216 33554432 50331648]


# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.


In [78]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr_swapped = arr.newbyteorder()
print("73. Array with swapped byte order:")
print(arr_swapped)

73. Array with swapped byte order:
[16777216 33554432 50331648]


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.


In [79]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':  # system endianness is native
    arr_swapped = arr.newbyteorder('>')
else:
    arr_swapped = arr.newbyteorder('<')
print("74. Conditionally swapped byte order array:")
print(arr_swapped)

74. Conditionally swapped byte order array:
[16777216 33554432 50331648]


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.


In [80]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("75. Byte swapping necessity:")
print(arr.dtype.byteorder != '=')

75. Byte swapping necessity:
False


# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.


In [81]:
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print("76. Original array after modifying copy:")
print(arr1)
print("76. Modified copy array:")
print(copy_arr)

76. Original array after modifying copy:
[ 1  2  3  4  5  6  7  8  9 10]
76. Modified copy array:
[100   2   3   4   5   6   7   8   9  10]


# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.


In [82]:
matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 100
print("77. Original matrix after modifying view:")
print(matrix)

77. Original matrix after modifying view:
[[100   2   6]
 [  9   5   1]
 [  3   6   6]]


# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.


In [83]:
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
print("78. Original array_a after broadcasting to view_b:")
print(array_a)

78. Original array_a after broadcasting to view_b:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.


In [84]:
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 100
print("79. Original array after modifying reshaped view:")
print(orig_array)

79. Original array after modifying reshaped view:
[[100   2   3   4]
 [  5   6   7   8]]


# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


In [85]:
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 100
print("80. Original data array after modifying copy:")
print(data)

80. Original data array after modifying copy:
[[1 9 2 2]
 [1 4 9 9]
 [5 5 1 4]]


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.


In [86]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("81. Matrix addition:")
print(A + B)
print("81. Matrix subtraction:")
print(A - B)

81. Matrix addition:
[[ 6  8]
 [10 12]]
81. Matrix subtraction:
[[-4 -4]
 [-4 -4]]


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.


In [87]:
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))
print("82. Matrix multiplication:")
print(np.dot(C, D))

82. Matrix multiplication:
[[40 64 36 72]
 [18 27 15 30]
 [22 28 15 30]]


# 83. Create a matrix `E` and find its transpose.


In [88]:
E = np.array([[1, 2, 3], [4, 5, 6]])
print("83. Transpose of matrix E:")
print(E.T)

83. Transpose of matrix E:
[[1 4]
 [2 5]
 [3 6]]


# 84. Generate a square matrix `F` and compute its determinant.


In [89]:
F = np.array([[1, 2], [3, 4]])
print("84. Determinant of matrix F:")
print(np.linalg.det(F))

84. Determinant of matrix F:
-2.0000000000000004


# 85. Create a square matrix `G` and find its inverse.


In [90]:
G = np.array([[1, 2], [3, 4]])
print("85. Inverse of matrix G:")
print(np.linalg.inv(G))

85. Inverse of matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
